# Generated by Django 5.2.7 on 2025-11-28 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_tontines',
            field=models.BooleanField(default=False, verbose_name='Peut créer des tontines'),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Le code d'invitation unique.", max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Indique si le code a déjà été utilisé.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.OneToOneField(blank=True, help_text="L'utilisateur qui a utilisé ce code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Code d'invitation",
                'verbose_name_plural': "Codes d'invitation",
            },
        ),
    ]
