# Generated by Django 5.2.6 on 2025-10-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_tontine_designated_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='current_round_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
