# Generated by Django 5.2.6 on 2025-10-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0003_tontine_current_round_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
