# Generated by Django 5.2.6 on 2025-09-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
