# Generated by Django 5.2.6 on 2025-10-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_contribution_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('unpaid', 'Non payé')], default='pending', max_length=20),
        ),
    ]
