# Generated by Django 5.2.6 on 2025-10-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_contribution_is_confirmed_contribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
